In [ ]:
import pandas as pd

In [ ]:
dmg=pd.read_csv("esea_master_dmg_demos.part1.csv")

In [ ]:
granada=pd.read_csv("esea_master_grenades_demos.part1.csv")

In [ ]:
kills=pd.read_csv("esea_master_kills_demos.part1.csv")

In [ ]:
meta=pd.read_csv("esea_meta_demos.part1.csv")

In [ ]:
meta['winner_team']

,file,map,round,start_seconds,end_seconds,winner_team,winner_side,round_type,ct_eq_val,t_eq_val
0,esea_match_13770997.dem,de_overpass,1,94.30782,160.9591,Hentai Hooligans,Terrorist,PISTOL_ROUND,4300,4250
1,esea_match_13770997.dem,de_overpass,2,160.95910,279.3998,Hentai Hooligans,Terrorist,ECO,6300,19400
2,esea_match_13770997.dem,de_overpass,3,279.39980,341.0084,Hentai Hooligans,Terrorist,SEMI_ECO,7650,19250
3,esea_match_13770997.dem,de_overpass,4,341.00840,435.4259,Hentai Hooligans,Terrorist,NORMAL,24900,23400
4,esea_match_13770997.dem,de_overpass,5,435.42590,484.2398,Animal Style,CounterTerrorist,ECO,5400,20550
...,...,...,...,...,...,...,...,...,...,...
215914,esea_match_13793043.dem,de_cache,14,1062.96100,1129.0460,Team 2,Terrorist,NORMAL,28400,25800
215915,esea_match_13793043.dem,de_cache,15,1129.04600,1185.9160,Team 1,CounterTerrorist,FORCE_BUY,13150,25550
215916,esea_match_13793043.dem,de_cache,16,1221.13300,1288.4690,Team 2,CounterTerrorist,PISTOL_ROUND,4200,4250
215917,esea_match_13793043.dem,de_cache,17,1288.46900,1342.4450,Team 2,CounterTerrorist,SEMI_ECO,18300,8200
215918,esea_match_13793043.dem,de_cache,18,1342.44500,1412.6290,Team 2,CounterTerrorist,SEMI_ECO,24400,9950

In [ ]:
mapas=pd.read_csv("map_data.csv")

In [ ]:
mapas

    Unnamed: 0  EndX  EndY  ResX  ResY  StartX  StartY
0     de_cache  3752  3187  1024  1024   -2031   -2240
1     de_cbble  2282  3032  1024  1024   -3819   -3073
2     de_dust2  2127  3455  1024  1024   -2486   -1150
3   de_inferno  2797  3800  1024  1024   -1960   -1062
4    de_mirage  1912  1682  1024  1024   -3217   -3401
5  de_overpass   503  1740  1024  1024   -4820   -3591
6     de_train  2262  2447  1024  1024   -2436   -2469

In [ ]:
meta.columns

Index(['file', 'map', 'round', 'start_seconds', 'end_seconds', 'winner_team',
       'winner_side', 'round_type', 'ct_eq_val', 't_eq_val'],
      dtype='object')

In [ ]:
kills['wp_type'].unique()

array(['Pistol', 'Rifle', 'Heavy', 'SMG', 'Sniper', 'Grenade',
       'Equipment', 'Unkown'], dtype=object)

In [ ]:
kills['wp'].unique()

array(['USP', 'Glock', 'AK47', 'Deagle', 'CZ', 'Negev', 'Mac10', 'M4A4',
       'P250', 'Bizon', 'AWP', 'P90', 'Famas', 'Swag7', 'MP9', 'UMP',
       'M4A1', 'FiveSeven', 'Gallil', 'XM1014', 'HE', 'Scout', 'Nova',
       'MP7', 'Scar20', 'Incendiary', 'AUG', 'P2000', 'Knife', 'SG556',
       'Tec9', 'SawedOff', 'DualBarettas', 'Zeus', 'G3SG1', 'Revolver',
       'World', 'M249', 'Flash', 'Molotov', 'Smoke'], dtype=object)

In [ ]:
kills.columns

Index(['file', 'round', 'tick', 'seconds', 'att_team', 'vic_team', 'att_side',
       'vic_side', 'wp', 'wp_type', 'ct_alive', 't_alive', 'is_bomb_planted'],
      dtype='object')

In [ ]:
kills[(kills['seconds']>400) & (kills['seconds'] < 480)].head()

,file,round,tick,seconds,att_team,vic_team,att_side,vic_side,wp,wp_type,ct_alive,t_alive,is_bomb_planted
4587,esea_match_13779818.dem,1,71366,426.0570,Team 2,Team 1,Terrorist,CounterTerrorist,Glock,Pistol,4,5,True
4588,esea_match_13779818.dem,1,71662,428.3737,Team 1,Team 2,CounterTerrorist,Terrorist,USP,Pistol,4,4,True
4589,esea_match_13779818.dem,1,72612,435.8091,Team 2,Team 1,Terrorist,CounterTerrorist,Glock,Pistol,3,4,True
4590,esea_match_13779818.dem,1,73284,441.0687,Team 2,Team 1,Terrorist,CounterTerrorist,Glock,Pistol,2,4,True
4591,esea_match_13779818.dem,1,73686,444.2151,Team 2,Team 1,Terrorist,CounterTerrorist,Glock,Pistol,1,4,True

In [ ]:
granada.columns

Index(['file', 'round', 'seconds', 'att_team', 'vic_team', 'att_id', 'vic_id',
       'att_side', 'vic_side', 'hp_dmg', 'arm_dmg', 'is_bomb_planted',
       'bomb_site', 'hitbox', 'nade', 'att_rank', 'vic_rank', 'att_pos_x',
       'att_pos_y', 'nade_land_x', 'nade_land_y', 'vic_pos_x', 'vic_pos_y'],
      dtype='object')

In [ ]:
dmg.columns

Index(['file', 'round', 'tick', 'seconds', 'att_team', 'vic_team', 'att_side',
       'vic_side', 'hp_dmg', 'arm_dmg', 'is_bomb_planted', 'bomb_site',
       'hitbox', 'wp', 'wp_type', 'att_id', 'att_rank', 'vic_id', 'vic_rank',
       'att_pos_x', 'att_pos_y', 'vic_pos_x', 'vic_pos_y'],
      dtype='object')

In [ ]:
granada['att_team'].unique()

array(['Animal Style', 'Hentai Hooligans', 'Team 1', 'Team 2', 'Endpoint',
       'fish123', 'Izako Boars', 'PACT', 'Team Kinguin', 'ONCA Gaming',
       'PRiDE', '--to be determined--', 'EURONICS Gaming', 'Sprout',
       'ALTERNATE aTTaX', 'AGO Esports'], dtype=object)

In [ ]:
len(granada.groupby(['att_team'])['file'].unique())

16

In [ ]:
len(granada.groupby(['att_team'])['att_id'].unique())

16

In [ ]:
len(granada['file'].unique())

8527

In [ ]:
granada['vic_team'].unique()

array([nan, 'Animal Style', 'Hentai Hooligans', 'Team 1', 'Team 2',
       'fish123', 'Endpoint', 'PACT', 'Izako Boars', 'Team Kinguin',
       'ONCA Gaming', 'PRiDE', '--to be determined--', 'EURONICS Gaming',
       'Sprout', 'ALTERNATE aTTaX', 'AGO Esports'], dtype=object)

In [ ]:
len(granada['file'].unique())

8527

In [ ]:
granada.groupby('att_id')['att_team'].unique()

att_id
76561197960269146    [Team 2, Team 1]
76561197960269474            [Team 2]
76561197960269624    [Team 2, Team 1]
76561197960269994    [Team 1, Team 2]
76561197960270087    [Team 1, Team 2]
                           ...
76561198853669756    [Team 2, Team 1]
76561198853689359    [Team 2, Team 1]
76561198853732518            [Team 2]
76561198853772878    [Team 2, Team 1]
76561198853849617            [Team 2]
Name: att_team, Length: 17842, dtype: object

In [ ]:
granada['file']

In [ ]:
granada.head()

,file,round,seconds,att_team,vic_team,att_id,vic_id,att_side,vic_side,hp_dmg,...,hitbox,nade,att_rank,vic_rank,att_pos_x,att_pos_y,nade_land_x,nade_land_y,vic_pos_x,vic_pos_y
0,esea_match_13770997.dem,1,153.1602,Animal Style,NaN,76561198165334141,NaN,CounterTerrorist,NaN,0,...,NaN,Smoke,0,NaN,-1618.146,-66.00259,-949.8569,-340.3019,NaN,NaN
1,esea_match_13770997.dem,2,184.7945,Hentai Hooligans,Animal Style,76561198037331400,7.656120e+16,Terrorist,CounterTerrorist,70,...,Generic,HE,0,0.0,-1719.904,-2357.64700,-2774.6650,-1603.9430,-2741.25,-1523.163
2,esea_match_13770997.dem,2,186.8617,Animal Style,NaN,76561198055191021,NaN,CounterTerrorist,NaN,0,...,NaN,HE,0,NaN,-1036.352,492.16760,-466.8676,-356.9641,NaN,NaN
3,esea_match_13770997.dem,2,187.1122,Animal Style,NaN,76561198055054795,NaN,CounterTerrorist,NaN,0,...,NaN,HE,0,NaN,-855.077,438.69090,-459.0147,-543.8581,NaN,NaN
4,esea_match_13770997.dem,2,191.0587,Hentai Hooligans,NaN,76561198037331400,NaN,Terrorist,NaN,0,...,NaN,Molotov,0,NaN,-2617.490,-1832.40700,-2743.5610,-927.2995,NaN,NaN

In [ ]:
granada.groupby('file')['att_id'].unique().apply(lambda x: len(x)).sum()

np.int64(86510)

In [ ]:
d=len(granada)

In [ ]:
mask= (((granada['vic_team']!= 'Team 1') & (granada['vic_team']!= 'Team 2')) & ((granada['att_team']!= 'Team 1') & (granada['att_team']!= 'Team 2')))

In [ ]:
s=len(granada[mask])
print(s)

7290

In [ ]:
d-s

2982770

In [ ]:
granada.groupby('att_team')['att_id'].nunique()

att_team
--to be determined--        5
AGO Esports                 5
ALTERNATE aTTaX             5
Animal Style                5
EURONICS Gaming             5
Endpoint                    5
Hentai Hooligans            5
Izako Boars                 5
ONCA Gaming                 5
PACT                        5
PRiDE                       5
Sprout                      5
Team 1                  14467
Team 2                  14556
Team Kinguin                5
fish123                     6
Name: att_id, dtype: int64

In [ ]:
granada[granada['att_team'] == 'Hentai Hooligans']['att_id'].nunique()

5

In [ ]:
len(granada['att_id'].unique())

17842

In [ ]:
granada['bomb_site'].unique()

array(['B', nan, 'A'], dtype=object)

In [ ]:
len(b)

5992097

In [ ]:
b['att_id'].unique()

array([                0, 76561198048742997, 76561198055054795, ...,
       76561198238323276, 76561198143208301, 76561198127318562],
      shape=(17870,))

In [ ]:
b['vic_id'].unique()

array([76561198055054795, 76561198082200410, 76561197961009213, ...,
       76561198238323276, 76561198143208301, 76561198127318562],
      shape=(17878,))

In [ ]:
b.columns

Index(['file', 'round', 'tick', 'seconds', 'att_team', 'vic_team', 'att_side',
       'vic_side', 'hp_dmg', 'arm_dmg', 'is_bomb_planted', 'bomb_site',
       'hitbox', 'wp', 'wp_type', 'att_id', 'att_rank', 'vic_id', 'vic_rank',
       'att_pos_x', 'att_pos_y', 'vic_pos_x', 'vic_pos_y'],
      dtype='object')

In [ ]:
b.iloc[:5,:]

,file,round,tick,seconds,att_team,vic_team,att_side,vic_side,hp_dmg,arm_dmg,...,wp,wp_type,att_id,att_rank,vic_id,vic_rank,att_pos_x,att_pos_y,vic_pos_x,vic_pos_y
0,esea_match_13770997.dem,1,14372,111.8476,World,Animal Style,NaN,CounterTerrorist,1,0,...,Unknown,Unkown,0,0,76561198055054795,0,0.0000,0.00000,0.0000,0.000000
1,esea_match_13770997.dem,1,15972,124.3761,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,18,9,...,USP,Pistol,76561198048742997,0,76561198082200410,0,-1499.6900,63.33829,-669.5558,-79.769570
2,esea_match_13770997.dem,1,16058,125.0495,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,100,0,...,USP,Pistol,76561198055054795,0,76561197961009213,0,-1066.8740,3.44563,-614.1868,-91.707770
3,esea_match_13770997.dem,1,16066,125.1121,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,12,7,...,Glock,Pistol,76561198082200410,0,76561198055054795,0,-747.3146,-49.32681,-1065.5560,9.381622
4,esea_match_13770997.dem,1,16108,125.4410,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,15,7,...,USP,Pistol,76561198048742997,0,76561198082200410,0,-1501.8610,49.19798,-748.4188,-53.469220

In [ ]:
b[b['att_rank']!=0]

Empty DataFrame
Columns: [file, round, tick, seconds, att_team, vic_team, att_side, vic_side, hp_dmg, arm_dmg, is_bomb_planted, bomb_site, hitbox, wp, wp_type, att_id, att_rank, vic_id, vic_rank, att_pos_x, att_pos_y, vic_pos_x, vic_pos_y]
Index: []

[0 rows x 23 columns]

In [ ]:
granada.head()

,file,round,seconds,att_team,vic_team,att_id,vic_id,att_side,vic_side,hp_dmg,...,hitbox,nade,att_rank,vic_rank,att_pos_x,att_pos_y,nade_land_x,nade_land_y,vic_pos_x,vic_pos_y
0,esea_match_13770997.dem,1,153.1602,Animal Style,NaN,76561198165334141,NaN,CounterTerrorist,NaN,0,...,NaN,Smoke,0,NaN,-1618.146,-66.00259,-949.8569,-340.3019,NaN,NaN
1,esea_match_13770997.dem,2,184.7945,Hentai Hooligans,Animal Style,76561198037331400,7.656120e+16,Terrorist,CounterTerrorist,70,...,Generic,HE,0,0.0,-1719.904,-2357.64700,-2774.6650,-1603.9430,-2741.25,-1523.163
2,esea_match_13770997.dem,2,186.8617,Animal Style,NaN,76561198055191021,NaN,CounterTerrorist,NaN,0,...,NaN,HE,0,NaN,-1036.352,492.16760,-466.8676,-356.9641,NaN,NaN
3,esea_match_13770997.dem,2,187.1122,Animal Style,NaN,76561198055054795,NaN,CounterTerrorist,NaN,0,...,NaN,HE,0,NaN,-855.077,438.69090,-459.0147,-543.8581,NaN,NaN
4,esea_match_13770997.dem,2,191.0587,Hentai Hooligans,NaN,76561198037331400,NaN,Terrorist,NaN,0,...,NaN,Molotov,0,NaN,-2617.490,-1832.40700,-2743.5610,-927.2995,NaN,NaN

In [ ]:
import numpy as np

b= np.random.randint(0,2)

if b == 1:
    print('jose chupalo')
else:
    print('jose no lo chupes, te quiero')

jose chupalo

In [ ]:
granada[granada['nade']=='Flash'].head()

,file,round,seconds,att_team,vic_team,att_id,vic_id,att_side,vic_side,hp_dmg,...,hitbox,nade,att_rank,vic_rank,att_pos_x,att_pos_y,nade_land_x,nade_land_y,vic_pos_x,vic_pos_y
6,esea_match_13770997.dem,2,191.6225,Animal Style,NaN,76561198165334141,NaN,CounterTerrorist,NaN,0,...,NaN,Flash,0,NaN,-1948.910,-1184.198,-1780.658,-976.403,NaN,NaN
10,esea_match_13770997.dem,3,306.8371,Hentai Hooligans,NaN,76561198037331400,NaN,Terrorist,NaN,0,...,NaN,Flash,0,NaN,-2115.314,-1922.654,-2684.468,-1329.793,NaN,NaN
21,esea_match_13770997.dem,4,365.3136,Hentai Hooligans,Animal Style,76561198133908390,7.656120e+16,Terrorist,CounterTerrorist,1,...,Generic,Flash,0,0.0,-1599.425,-2401.576,-2634.119,-1692.584,-2649.508,-1708.464
22,esea_match_13770997.dem,4,365.3136,Hentai Hooligans,Animal Style,76561198133908390,7.656120e+16,Terrorist,CounterTerrorist,1,...,Generic,Flash,0,0.0,-1599.425,-2401.576,-2634.119,-1692.584,-2649.508,-1708.464
23,esea_match_13770997.dem,4,365.8461,Hentai Hooligans,NaN,76561198037331400,NaN,Terrorist,NaN,0,...,NaN,Flash,0,NaN,-1618.814,-2410.170,-2586.813,-1741.313,NaN,NaN

In [ ]:
granada['nade'].unique()

array(['Smoke', 'HE', 'Molotov', 'Flash', 'Incendiary', 'Decoy'],
      dtype=object)

In [ ]:
dmg['hitbox'].unique()

array(['Generic', 'Stomach', 'Head', 'RightArm', 'Chest', 'LeftArm',
       'RightLeg', 'LeftLeg', '8'], dtype=object)